### ISSUE TITLE
[PROFILE] Manage account (google) returns a 400

### ISSUE THREAD

**Issue by alvaromarins** [bradleygunnraver/sharescape#39]
**Discovered on:**
MacOs Mojave 10.14.12 - Google Chrome 71.0.0.3578.98 (64-bit)

**URL/environment:**
https://accounts.google.com/o/oauth2/v2/auth?response....

**Steps to recreate**
Log into your account
Navigate to account > manage > google
Observe result

**Description**
When managing account and proceeding with a google account, account.google.com service returns a 400

**Comment by bradleygunnraver** [comment]
Google authentication to be added back in later with #50
